USE StayActive;

CREATE TABLE workout (
                         id BIGINT PRIMARY AUTO_INCREMENT KEY,
                         ime VARCHAR(20) NOT NULL,
                         opis VARCHAR(50) NOT NULL,
                         broj_ponavljanja INT NOT NULL,
                         tezina_vjezbe VARCHAR(255) NOT NULL
);

INSERT INTO workout (broj_ponavljanja, ime, opis, tezina_vjezbe) VALUES
                                                                        (230, 'Sklekovi', 'Za jačanje Ruka i Prsa', 'Normalan'),
                                                                        (350, 'Trbušnjaci', 'Za jačanje Abdomena', 'Napredan'),
                                                                        (120, 'Čučnjevi', 'Za Jačanje Noga i Stražnjice', 'Početnik'),
                                                                        (510, 'Iskoraci', 'Za Jačanje Noga i Stražnjice', 'Profesionalac'),
                                                                        (270, 'Zgibovi', 'Za Jačanje leđa i Ruka', 'Normalan'),
                                                                        (90, 'Sprintovi', 'Za Jačanje Noga i Stražnjice', 'Početnik'),
                                                                        (420, 'Propadanja', 'Za Jačanje leđa i Ruka', 'Napredan'),
                                                                        (200, 'Sklekovi', 'Za jačanje Ruka i Prsa', 'Normalan'),
                                                                        (550, 'Trbušnjaci', 'Za jačanje Abdomena', 'Profesionalac'),
                                                                        (60, 'Čučnjevi', 'Za Jačanje Noga i Stražnjice', 'Početnik'),
                                                                        ( 320, 'Iskoraci', 'Za Jačanje Noga i Stražnjice', 'Napredan'),
                                                                        ( 450, 'Zgibovi', 'Za Jačanje leđa i Ruka', 'Normalan'),
                                                                        ( 150, 'Sprintovi', 'Za Jačanje Noga i Stražnjice', 'Početnik'),
                                                                        ( 210, 'Propadanja', 'Za Jačanje leđa i Ruka', 'Normalan'),
                                                                        ( 340, 'Sklekovi', 'Za jačanje Ruka i Prsa', 'Napredan'),
                                                                        ( 290, 'Trbušnjaci', 'Za jačanje Abdomena', 'Napredan'),
                                                                        ( 70, 'Čučnjevi', 'Za Jačanje Noga i Stražnjice', 'Početnik'),
                                                                        ( 500, 'Iskoraci', 'Za Jačanje Noga i Stražnjice', 'Profesionalac'),
                                                                        ( 230, 'Zgibovi', 'Za Jačanje leđa i Ruka', 'Normalan'),
                                                                        ( 340, 'Sprintovi', 'Za Jačanje Noga i Stražnjice', 'Napredan'),
                                                                        ( 120, 'Propadanja', 'Za Jačanje leđa i Ruka', 'Normalan'),
                                                                        ( 670, 'Sklekovi', 'Za jačanje Ruka i Prsa', 'Napredan'),
                                                                        ( 480, 'Trbušnjaci', 'Za jačanje Abdomena', 'Profesionalac'),
                                                                        ( 380, 'Čučnjevi', 'Za Jačanje Noga i Stražnjice', 'Napredan'),
                                                                        ( 200, 'Iskoraci', 'Za Jačanje Noga i Stražnjice', 'Početnik'),
                                                                        ( 330, 'Zgibovi', 'Za Jačanje leđa i Ruka', 'Napredan'),
                                                                        ( 160, 'Sprintovi', 'Za Jačanje Noga i Stražnjice', 'Početnik'),
                                                                        ( 370, 'Propadanja', 'Za Jačanje leđa i Ruka', 'Napredan'),
                                                                        ( 600, 'Sklekovi', 'Za jačanje Ruka i Prsa', 'Napredan'),
                                                                        ( 310, 'Trbušnjaci', 'Za jačanje Abdomena', 'Napredan'),
                                                                        ( 480, 'Čučnjevi', 'Za Jačanje Noga i Stražnjice', 'Napredan'),
                                                                        ( 230, 'Iskoraci', 'Za Jačanje Noga i Stražnjice', 'Napredan'),
                                                                        ( 150, 'Zgibovi', 'Za Jačanje leđa i Ruka', 'Napredan'),
                                                                        ( 110, 'Sprintovi', 'Za Jačanje Noga i Stražnjice', 'Početnik'),
                                                                        ( 350, 'Propadanja', 'Za Jačanje leđa i Ruka', 'Napredan'),
                                                                        ( 670, 'Sklekovi', 'Za jačanje Ruka i Prsa', 'Profesionalac'),
                                                                        ( 290, 'Trbušnjaci', 'Za jačanje Abdomena', 'Napredan'),
                                                                        ( 340, 'Čučnjevi', 'Za Jačanje Noga i Stražnjice', 'Napredan'),
                                                                        ( 270, 'Iskoraci', 'Za Jačanje Noga i Stražnjice', 'Profesionalac'),
                                                                        ( 130, 'Zgibovi', 'Za Jačanje leđa i Ruka', 'Profesionalac'),
                                                                        ( 300, 'Sprintovi', 'Za Jačanje Noga i Stražnjice', 'Napredan'),
                                                                        ( 460, 'Propadanja', 'Za Jačanje leđa i Ruka', 'Profesionalac'),
                                                                        ( 330, 'Sklekovi', 'Za jačanje Ruka i Prsa', 'Profesionalac'),
                                                                        ( 390, 'Trbušnjaci', 'Za jačanje Abdomena', 'Profesionalac'),
                                                                        ( 240, 'Čučnjevi', 'Za Jačanje Noga i Stražnjice', 'Profesionalac'),
                                                                        ( 500, 'Iskoraci', 'Za Jačanje Noga i Stražnjice', 'Profesionalac'),
                                                                        ( 420, 'Zgibovi', 'Za Jačanje leđa i Ruka', 'Profesionalac'),
                                                                        ( 110, 'Sprintovi', 'Za Jačanje Noga i Stražnjice', 'Početnik'),
                                                                        ( 350, 'Propadanja', 'Za Jačanje leđa i Ruka', 'Napredan'),
                                                                        ( 630, 'Sklekovi', 'Za jačanje Ruka i Prsa', 'Profesionalac'),
                                                                        ( 220, 'Trbušnjaci', 'Za jačanje Abdomena', 'Profesionalac'),
                                                                        ( 370, 'Čučnjevi', 'Za Jačanje Noga i Stražnjice', 'Profesionalac'),
                                                                        ( 260, 'Iskoraci', 'Za Jačanje Noga i Stražnjice', 'Profesionalac'),
                                                                        ( 170, 'Zgibovi', 'Za Jačanje leđa i Ruka', 'Profesionalac'),
                                                                        ( 220, 'Sprintovi', 'Za Jačanje Noga i Stražnjice', 'Profesionalac'),
                                                                        ( 480, 'Propadanja', 'Za Jačanje leđa i Ruka', 'Profesionalac'),
                                                                        ( 340, 'Sklekovi', 'Za jačanje Ruka i Prsa', 'Profesionalac'),
                                                                        ( 390, 'Trbušnjaci', 'Za jačanje Abdomena', 'Profesionalac'),
                                                                        ( 230, 'Čučnjevi', 'Za Jačanje Noga i Stražnjice', 'Profesionalac'),
                                                                        ( 500, 'Iskoraci', 'Za Jačanje Noga i Stražnjice', 'Profesionalac'),
                                                                        ( 390, 'Zgibovi', 'Za Jačanje leđa i Ruka', 'Napredan'),
                                                                        ( 120, 'Sprintovi', 'Za Jačanje Noga i Stražnjice', 'Početnik'),
                                                                        ( 260, 'Propadanja', 'Za Jačanje leđa i Ruka', 'Napredan'),
                                                                        ( 690, 'Sklekovi', 'Za jačanje Ruka i Prsa', 'Profesionalac'),
                                                                        ( 260, 'Trbušnjaci', 'Za jačanje Abdomena', 'Profesionalac'),
                                                                        ( 360, 'Čučnjevi', 'Za Jačanje Noga i Stražnjice', 'Napredan'),
                                                                        ( 430, 'Iskoraci', 'Za Jačanje Noga i Stražnjice', 'Profesionalac'),
                                                                        ( 160, 'Zgibovi', 'Za Jačanje leđa i Ruka', 'Napredan'),
                                                                        ( 430, 'Sprintovi', 'Za Jačanje Noga i Stražnjice', 'Profesionalac'),
                                                                        ( 230, 'Propadanja', 'Za Jačanje leđa i Ruka', 'Napredan'),
                                                                        ( 650, 'Sklekovi', 'Za jačanje Ruka i Prsa', 'Profesionalac'),
                                                                        ( 350, 'Trbušnjaci', 'Za jačanje Abdomena', 'Profesionalac'),
                                                                        ( 190, 'Čučnjevi', 'Za Jačanje Noga i Stražnjice', 'Napredan'),
                                                                        ( 370, 'Iskoraci', 'Za Jačanje Noga i Stražnjice', 'Profesionalac'),
                                                                        ( 500, 'Zgibovi', 'Za Jačanje leđa i Ruka', 'Napredan'),
                                                                        ( 280, 'Sprintovi', 'Za Jačanje Noga i Stražnjice', 'Profesionalac'),
                                                                        ( 460, 'Propadanja', 'Za Jačanje leđa i Ruka', 'Napredan'),
                                                                        ( 340, 'Sklekovi', 'Za jačanje Ruka i Prsa', 'Profesionalac'),
                                                                        ( 290, 'Trbušnjaci', 'Za jačanje Abdomena', 'Profesionalac'),
                                                                        ( 170, 'Čučnjevi', 'Za Jačanje Noga i Stražnjice', 'Napredan'),
                                                                        ( 410, 'Iskoraci', 'Za Jačanje Noga i Stražnjice', 'Profesionalac'),
                                                                        ( 560, 'Zgibovi', 'Za Jačanje leđa i Ruka', 'Napredan'),
                                                                        ( 290, 'Sprintovi', 'Za Jačanje Noga i Stražnjice', 'Profesionalac'),
                                                                        ( 370, 'Propadanja', 'Za Jačanje leđa i Ruka', 'Napredan'),
                                                                        ( 600, 'Sklekovi', 'Za jačanje Ruka i Prsa', 'Napredan'),
                                                                        ( 450, 'Trbušnjaci', 'Za jačanje Abdomena', 'Profesionalac'),
                                                                        ( 170, 'Čučnjevi', 'Za Jačanje Noga i Stražnjice', 'Napredan'),
                                                                        ( 260, 'Iskoraci', 'Za Jačanje Noga i Stražnjice', 'Profesionalac'),
                                                                        ( 130, 'Zgibovi', 'Za Jačanje leđa i Ruka', 'Napredan'),
                                                                        ( 380, 'Sprintovi', 'Za Jačanje Noga i Stražnjice', 'Profesionalac'),
                                                                        ( 140, 'Propadanja', 'Za Jačanje leđa i Ruka', 'Napredan'),
                                                                        ( 700, 'Sklekovi', 'Za jačanje Ruka i Prsa', 'Profesionalac'),
                                                                        ( 330, 'Trbušnjaci', 'Za jačanje Abdomena', 'Profesionalac'),
                                                                        ( 270, 'Čučnjevi', 'Za Jačanje Noga i Stražnjice', 'Napredan'),
                                                                        ( 360, 'Iskoraci', 'Za Jačanje Noga i Stražnjice', 'Profesionalac');