USE StayActive;

CREATE TABLE user (
                       id INT PRIMARY KEY AUTO_INCREMENT,
                       ime VARCHAR(20) NOT NULL,
                       prezime VARCHAR(20) NOT NULL,
                       email VARCHAR(255) NOT NULL,
                       lozinka VARCHAR(255) NOT NULL,
                       role ENUM('KORISNIK', 'TRENER') NOT NULL
);

INSERT INTO user (id , ime, prezime, email, lozinka, role) VALUES (900,'Filip','Peric','fifi.peri3@gmail.com','$2a$10$xV3fheyHBrC5/mfsWWa9FOs8ShSRlnWAiIhLbL4VGVSNMbjBDWksC','TRENER');

CREATE TABLE workout (
                         id BIGINT AUTO_INCREMENT PRIMARY KEY,
                         ime VARCHAR(20) NOT NULL,
                         opis VARCHAR(50) NOT NULL,
                         broj_ponavljanja INT NOT NULL,
                         tezina_vjezbe VARCHAR(255) NOT NULL
);
INSERT INTO workout (broj_ponavljanja, ime, opis, tezina_vjezbe) VALUES
(230, 'Sklekovi', 'Za jačanje Ruka i Prsa', 'Normalan'),
(350, 'Trbusnjaci', 'Za jačanje Abdomena', 'Napredan'),
(120, 'Cucnjevi', 'Za Jacanje Noga i Straznjice', 'Pocetnik'),
(510, 'Iskoraci', 'Za Jacanje Noga i Straznjice', 'Profesionalac'),
(270, 'Zgibovi', 'Za Jacanje leda i Ruka', 'Normalan'),
(90, 'Sprintovi', 'Za Jacanje Noga i Straznjice', 'Pocetnik'),
(420, 'Propadanja', 'Za Jacanje leda i Ruka', 'Napredan'),
(200, 'Sklekovi', 'Za jacanje Ruka i Prsa', 'Normalan'),
(550, 'Trbusnjaci', 'Za jacanje Abdomena', 'Profesionalac'),
(60, 'Cucnjevi', 'Za Jacanje Noga i Straznjice', 'Pocetnik'),
(320, 'Iskoraci', 'Za Jacanje Noga i Straznjice', 'Napredan'),
(450, 'Zgibovi', 'Za Jacanje leda i Ruka', 'Normalan'),
(150, 'Sprintovi', 'Za Jacanje Noga i Straznjice', 'Pocetnik'),
(210, 'Propadanja', 'Za Jacanje leda i Ruka', 'Normalan'),
(340, 'Sklekovi', 'Za jacanje Ruka i Prsa', 'Napredan'),
(290, 'Trbusnjaci', 'Za jacanje Abdomena', 'Napredan'),
(70, 'Cucnjevi', 'Za Jacanje Noga i Straznjice', 'Pocetnik'),
(500, 'Iskoraci', 'Za Jacanje Noga i Straznjice', 'Profesionalac'),
(230, 'Zgibovi', 'Za Jacanje leda i Ruka', 'Normalan'),
(340, 'Sprintovi', 'Za Jacanje Noga i Straznjice', 'Napredan'),
(120, 'Propadanja', 'Za Jacanje leda i Ruka', 'Normalan'),
(670, 'Sklekovi', 'Za jacanje Ruka i Prsa', 'Napredan'),
(480, 'Trbusnjaci', 'Za jacanje Abdomena', 'Profesionalac'),
(380, 'Cucnjevi', 'Za Jacanje Noga i Straznjice', 'Napredan'),
(200, 'Iskoraci', 'Za Jacanje Noga i Straznjice', 'Pocetnik'),
(330, 'Zgibovi', 'Za Jacanje leda i Ruka', 'Napredan'),
(160, 'Sprintovi', 'Za Jacanje Noga i Straznjice', 'Pocetnik'),
(370, 'Propadanja', 'Za Jacanje leda i Ruka', 'Napredan'),
(600, 'Sklekovi', 'Za jacanje Ruka i Prsa', 'Napredan'),
(310, 'Trbusnjaci', 'Za jacanje Abdomena', 'Napredan'),
(480, 'Cucnjevi', 'Za Jacanje Noga i Straznjice', 'Napredan'),
(230, 'Iskoraci', 'Za Jacanje Noga i Straznjice', 'Napredan'),
(150, 'Zgibovi', 'Za Jacanje leda i Ruka', 'Napredan'),
(110, 'Sprintovi', 'Za Jacanje Noga i Straznjice', 'Pocetnik'),
(350, 'Propadanja', 'Za Jacanje leda i Ruka', 'Napredan'),
(670, 'Sklekovi', 'Za jacanje Ruka i Prsa', 'Profesionalac'),
(290, 'Trbusnjaci', 'Za jacanje Abdomena', 'Napredan'),
(340, 'Cucnjevi', 'Za Jacanje Noga i Straznjice', 'Napredan'),
(270, 'Iskoraci', 'Za Jacanje Noga i Straznjice', 'Profesionalac'),
(130, 'Zgibovi', 'Za Jacanje leda i Ruka', 'Profesionalac'),
(300, 'Sprintovi', 'Za Jacanje Noga i Straznjice', 'Napredan'),
(460, 'Propadanja', 'Za Jacanje leda i Ruka', 'Profesionalac'),
(330, 'Sklekovi', 'Za jacanje Ruka i Prsa', 'Profesionalac'),
(390, 'Trbusnjaci', 'Za jacanje Abdomena', 'Profesionalac'),
(240, 'Cucnjevi', 'Za Jacanje Noga i Straznjice', 'Profesionalac'),
(500, 'Iskoraci', 'Za Jacanje Noga i Straznjice', 'Profesionalac'),
(420, 'Zgibovi', 'Za Jacanje leda i Ruka', 'Profesionalac'),
(110, 'Sprintovi', 'Za Jacanje Noga i Straznjice', 'Pocetnik'),
(350, 'Propadanja', 'Za Jacanje leda i Ruka', 'Napredan'),
(630, 'Sklekovi', 'Za jacanje Ruka i Prsa', 'Profesionalac'),
(220, 'Trbusnjaci', 'Za jacanje Abdomena', 'Profesionalac'),
(370, 'Cucnjevi', 'Za Jacanje Noga i Straznjice', 'Profesionalac'),
(260, 'Iskoraci', 'Za Jacanje Noga i Straznjice', 'Profesionalac'),
(170, 'Zgibovi', 'Za Jacanje leda i Ruka', 'Profesionalac'),
(220, 'Sprintovi', 'Za Jacanje Noga i Straznjice', 'Profesionalac'),
(480, 'Propadanja', 'Za Jacanje leda i Ruka', 'Profesionalac'),
(340, 'Sklekovi', 'Za jacanje Ruka i Prsa', 'Profesionalac'),
(390, 'Trbusnjaci', 'Za jacanje Abdomena', 'Profesionalac'),
(230, 'Cucnjevi', 'Za Jacanje Noga i Straznjice', 'Profesionalac'),
(500, 'Iskoraci', 'Za Jacanje Noga i Straznjice', 'Profesionalac'),
(390, 'Zgibovi', 'Za Jacanje leda i Ruka', 'Napredan'),
(120, 'Sprintovi', 'Za Jacanje Noga i Straznjice', 'Pocetnik'),
(260, 'Propadanja', 'Za Jacanje leda i Ruka', 'Napredan'),
(690, 'Sklekovi', 'Za jacanje Ruka i Prsa', 'Profesionalac'),
(260, 'Trbusnjaci', 'Za jacanje Abdomena', 'Profesionalac'),
(360, 'Cucnjevi', 'Za Jacanje Noga i Straznjice', 'Napredan'),
(430, 'Iskoraci', 'Za Jacanje Noga i Straznjice', 'Profesionalac'),
(160, 'Zgibovi', 'Za Jacanje leda i Ruka', 'Napredan'),
(430, 'Sprintovi', 'Za Jacanje Noga i Straznjice', 'Profesionalac'),
(230, 'Propadanja', 'Za Jacanje leda i Ruka', 'Napredan'),
(650, 'Sklekovi', 'Za jacanje Ruka i Prsa', 'Profesionalac'),
(350, 'Trbusnjaci', 'Za jacanje Abdomena', 'Profesionalac'),
(190, 'Cucnjevi', 'Za Jacanje Noga i Straznjice', 'Napredan'),
(370, 'Iskoraci', 'Za Jacanje Noga i Straznjice', 'Profesionalac');