USE StayActive;

ALTER TABLE workout MODIFY opis VARCHAR(50);

INSERT INTO workout (id, broj_ponavljanja, ime, opis, tezina_vjezbe) VALUES
                                                                        (0, 230, 'Sklekovi', 'Za jačanje Ruka i Prsa', 'Normalan'),
                                                                        (1, 350, 'Trbušnjaci', 'Za jačanje Abdomena', 'Napredan'),
                                                                        (2, 120, 'Čučnjevi', 'Za Jačanje Noga i Stražnjice', 'Početnik'),
                                                                        (3, 510, 'Iskoraci', 'Za Jačanje Noga i Stražnjice', 'Profesionalac'),
                                                                        (4, 270, 'Zgibovi', 'Za Jačanje leđa i Ruka', 'Normalan'),
                                                                        (5, 90, 'Sprintovi', 'Za Jačanje Noga i Stražnjice', 'Početnik'),
                                                                        (6, 420, 'Propadanja', 'Za Jačanje leđa i Ruka', 'Napredan'),
                                                                        (7, 200, 'Sklekovi', 'Za jačanje Ruka i Prsa', 'Normalan'),
                                                                        (8, 550, 'Trbušnjaci', 'Za jačanje Abdomena', 'Profesionalac'),
                                                                        (9, 60, 'Čučnjevi', 'Za Jačanje Noga i Stražnjice', 'Početnik'),
                                                                        (10, 320, 'Iskoraci', 'Za Jačanje Noga i Stražnjice', 'Napredan'),
                                                                        (11, 450, 'Zgibovi', 'Za Jačanje leđa i Ruka', 'Normalan'),
                                                                        (12, 150, 'Sprintovi', 'Za Jačanje Noga i Stražnjice', 'Početnik'),
                                                                        (13, 210, 'Propadanja', 'Za Jačanje leđa i Ruka', 'Normalan'),
                                                                        (14, 340, 'Sklekovi', 'Za jačanje Ruka i Prsa', 'Napredan'),
                                                                        (15, 290, 'Trbušnjaci', 'Za jačanje Abdomena', 'Napredan'),
                                                                        (16, 70, 'Čučnjevi', 'Za Jačanje Noga i Stražnjice', 'Početnik'),
                                                                        (17, 500, 'Iskoraci', 'Za Jačanje Noga i Stražnjice', 'Profesionalac'),
                                                                        (18, 230, 'Zgibovi', 'Za Jačanje leđa i Ruka', 'Normalan'),
                                                                        (19, 340, 'Sprintovi', 'Za Jačanje Noga i Stražnjice', 'Napredan'),
                                                                        (20, 120, 'Propadanja', 'Za Jačanje leđa i Ruka', 'Normalan'),
                                                                        (21, 670, 'Sklekovi', 'Za jačanje Ruka i Prsa', 'Napredan'),
                                                                        (22, 480, 'Trbušnjaci', 'Za jačanje Abdomena', 'Profesionalac'),
                                                                        (23, 380, 'Čučnjevi', 'Za Jačanje Noga i Stražnjice', 'Napredan'),
                                                                        (24, 200, 'Iskoraci', 'Za Jačanje Noga i Stražnjice', 'Početnik'),
                                                                        (25, 330, 'Zgibovi', 'Za Jačanje leđa i Ruka', 'Napredan'),
                                                                        (26, 160, 'Sprintovi', 'Za Jačanje Noga i Stražnjice', 'Početnik'),
                                                                        (27, 370, 'Propadanja', 'Za Jačanje leđa i Ruka', 'Napredan'),
                                                                        (28, 600, 'Sklekovi', 'Za jačanje Ruka i Prsa', 'Napredan'),
                                                                        (29, 310, 'Trbušnjaci', 'Za jačanje Abdomena', 'Napredan'),
                                                                        (30, 480, 'Čučnjevi', 'Za Jačanje Noga i Stražnjice', 'Napredan'),
                                                                        (31, 230, 'Iskoraci', 'Za Jačanje Noga i Stražnjice', 'Napredan'),
                                                                        (32, 150, 'Zgibovi', 'Za Jačanje leđa i Ruka', 'Napredan'),
                                                                        (33, 110, 'Sprintovi', 'Za Jačanje Noga i Stražnjice', 'Početnik'),
                                                                        (34, 350, 'Propadanja', 'Za Jačanje leđa i Ruka', 'Napredan'),
                                                                        (35, 670, 'Sklekovi', 'Za jačanje Ruka i Prsa', 'Profesionalac'),
                                                                        (36, 290, 'Trbušnjaci', 'Za jačanje Abdomena', 'Napredan'),
                                                                        (37, 340, 'Čučnjevi', 'Za Jačanje Noga i Stražnjice', 'Napredan'),
                                                                        (38, 270, 'Iskoraci', 'Za Jačanje Noga i Stražnjice', 'Profesionalac'),
                                                                        (39, 130, 'Zgibovi', 'Za Jačanje leđa i Ruka', 'Profesionalac'),
                                                                        (40, 300, 'Sprintovi', 'Za Jačanje Noga i Stražnjice', 'Napredan'),
                                                                        (41, 460, 'Propadanja', 'Za Jačanje leđa i Ruka', 'Profesionalac'),
                                                                        (42, 330, 'Sklekovi', 'Za jačanje Ruka i Prsa', 'Profesionalac'),
                                                                        (43, 390, 'Trbušnjaci', 'Za jačanje Abdomena', 'Profesionalac'),
                                                                        (44, 240, 'Čučnjevi', 'Za Jačanje Noga i Stražnjice', 'Profesionalac'),
                                                                        (45, 500, 'Iskoraci', 'Za Jačanje Noga i Stražnjice', 'Profesionalac'),
                                                                        (46, 420, 'Zgibovi', 'Za Jačanje leđa i Ruka', 'Profesionalac'),
                                                                        (47, 110, 'Sprintovi', 'Za Jačanje Noga i Stražnjice', 'Početnik'),
                                                                        (48, 350, 'Propadanja', 'Za Jačanje leđa i Ruka', 'Napredan'),
                                                                        (49, 630, 'Sklekovi', 'Za jačanje Ruka i Prsa', 'Profesionalac'),
                                                                        (50, 220, 'Trbušnjaci', 'Za jačanje Abdomena', 'Profesionalac'),
                                                                        (51, 370, 'Čučnjevi', 'Za Jačanje Noga i Stražnjice', 'Profesionalac'),
                                                                        (52, 260, 'Iskoraci', 'Za Jačanje Noga i Stražnjice', 'Profesionalac'),
                                                                        (53, 170, 'Zgibovi', 'Za Jačanje leđa i Ruka', 'Profesionalac'),
                                                                        (54, 220, 'Sprintovi', 'Za Jačanje Noga i Stražnjice', 'Profesionalac'),
                                                                        (55, 480, 'Propadanja', 'Za Jačanje leđa i Ruka', 'Profesionalac'),
                                                                        (56, 340, 'Sklekovi', 'Za jačanje Ruka i Prsa', 'Profesionalac'),
                                                                        (57, 390, 'Trbušnjaci', 'Za jačanje Abdomena', 'Profesionalac'),
                                                                        (58, 230, 'Čučnjevi', 'Za Jačanje Noga i Stražnjice', 'Profesionalac'),
                                                                        (59, 500, 'Iskoraci', 'Za Jačanje Noga i Stražnjice', 'Profesionalac'),
                                                                        (60, 390, 'Zgibovi', 'Za Jačanje leđa i Ruka', 'Napredan'),
                                                                        (61, 120, 'Sprintovi', 'Za Jačanje Noga i Stražnjice', 'Početnik'),
                                                                        (62, 260, 'Propadanja', 'Za Jačanje leđa i Ruka', 'Napredan'),
                                                                        (63, 690, 'Sklekovi', 'Za jačanje Ruka i Prsa', 'Profesionalac'),
                                                                        (64, 260, 'Trbušnjaci', 'Za jačanje Abdomena', 'Profesionalac'),
                                                                        (65, 360, 'Čučnjevi', 'Za Jačanje Noga i Stražnjice', 'Napredan'),
                                                                        (66, 430, 'Iskoraci', 'Za Jačanje Noga i Stražnjice', 'Profesionalac'),
                                                                        (67, 160, 'Zgibovi', 'Za Jačanje leđa i Ruka', 'Napredan'),
                                                                        (68, 430, 'Sprintovi', 'Za Jačanje Noga i Stražnjice', 'Profesionalac'),
                                                                        (69, 230, 'Propadanja', 'Za Jačanje leđa i Ruka', 'Napredan'),
                                                                        (70, 650, 'Sklekovi', 'Za jačanje Ruka i Prsa', 'Profesionalac'),
                                                                        (71, 350, 'Trbušnjaci', 'Za jačanje Abdomena', 'Profesionalac'),
                                                                        (72, 190, 'Čučnjevi', 'Za Jačanje Noga i Stražnjice', 'Napredan'),
                                                                        (73, 370, 'Iskoraci', 'Za Jačanje Noga i Stražnjice', 'Profesionalac'),
                                                                        (74, 500, 'Zgibovi', 'Za Jačanje leđa i Ruka', 'Napredan'),
                                                                        (75, 280, 'Sprintovi', 'Za Jačanje Noga i Stražnjice', 'Profesionalac'),
                                                                        (76, 460, 'Propadanja', 'Za Jačanje leđa i Ruka', 'Napredan'),
                                                                        (77, 340, 'Sklekovi', 'Za jačanje Ruka i Prsa', 'Profesionalac'),
                                                                        (78, 290, 'Trbušnjaci', 'Za jačanje Abdomena', 'Profesionalac'),
                                                                        (79, 170, 'Čučnjevi', 'Za Jačanje Noga i Stražnjice', 'Napredan'),
                                                                        (80, 410, 'Iskoraci', 'Za Jačanje Noga i Stražnjice', 'Profesionalac'),
                                                                        (81, 560, 'Zgibovi', 'Za Jačanje leđa i Ruka', 'Napredan'),
                                                                        (82, 290, 'Sprintovi', 'Za Jačanje Noga i Stražnjice', 'Profesionalac'),
                                                                        (83, 370, 'Propadanja', 'Za Jačanje leđa i Ruka', 'Napredan'),
                                                                        (84, 600, 'Sklekovi', 'Za jačanje Ruka i Prsa', 'Napredan'),
                                                                        (85, 450, 'Trbušnjaci', 'Za jačanje Abdomena', 'Profesionalac'),
                                                                        (86, 170, 'Čučnjevi', 'Za Jačanje Noga i Stražnjice', 'Napredan'),
                                                                        (87, 260, 'Iskoraci', 'Za Jačanje Noga i Stražnjice', 'Profesionalac'),
                                                                        (88, 130, 'Zgibovi', 'Za Jačanje leđa i Ruka', 'Napredan'),
                                                                        (89, 380, 'Sprintovi', 'Za Jačanje Noga i Stražnjice', 'Profesionalac'),
                                                                        (90, 140, 'Propadanja', 'Za Jačanje leđa i Ruka', 'Napredan'),
                                                                        (91, 700, 'Sklekovi', 'Za jačanje Ruka i Prsa', 'Profesionalac'),
                                                                        (92, 330, 'Trbušnjaci', 'Za jačanje Abdomena', 'Profesionalac'),
                                                                        (93, 270, 'Čučnjevi', 'Za Jačanje Noga i Stražnjice', 'Napredan'),
                                                                        (94, 360, 'Iskoraci', 'Za Jačanje Noga i Stražnjice', 'Profesionalac');